package org.jfree.chart.renderer.category;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.util.List;

import org.jfree.chart.ChartRenderingInfo;
import org.jfree.chart.LegendItem;
import org.jfree.chart.LegendItemCollection;
import org.jfree.chart.annotations.CategoryAnnotation;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.labels.CategoryItemLabelGenerator;
import org.jfree.chart.labels.CategorySeriesLabelGenerator;
import org.jfree.chart.labels.CategoryToolTipGenerator;
import org.jfree.chart.labels.StandardCategorySeriesLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotRenderingInfo;
import org.jfree.chart.urls.CategoryURLGenerator;
import org.jfree.chart.util.Layer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

import junit.framework.TestCase;

/**
 * Regression tests for AbstractCategoryItemRenderer.
 * Tests concrete methods of the abstract base class using a minimal
 * concrete implementation.
 * 
 * Prompt Iteration: 2 (coursework context clarified)
 * Attribution: Generated by Claude Haiku, KKU IntelSphere experimental workflow
 * Source: Chart fixed revision 1f, org.jfree.chart.renderer.category package
 */
public class AbstractCategoryItemRendererTest extends TestCase {

    /**
     * Minimal concrete implementation for testing AbstractCategoryItemRenderer.
     * Implements only abstract methods without additional rendering logic.
     */
    private static class ConcreteRenderer extends AbstractCategoryItemRenderer {
        @Override
        public void drawItem(Graphics2D g2, CategoryItemRendererState state,
                Rectangle2D dataArea, CategoryPlot plot, CategoryAxis domainAxis,
                org.jfree.chart.axis.ValueAxis rangeAxis,
                CategoryDataset dataset, int row, int column) {
            // No-op implementation for testing
        }
    }

    private ConcreteRenderer renderer;
    private CategoryPlot plot;
    private DefaultCategoryDataset dataset;
    private CategoryAxis domainAxis;
    private NumberAxis rangeAxis;

    @Override
    protected void setUp() throws Exception {
        super.setUp();
        renderer = new ConcreteRenderer();
        dataset = new DefaultCategoryDataset();
        dataset.addValue(10.0, "Series 1", "Category A");
        dataset.addValue(20.0, "Series 1", "Category B");
        dataset.addValue(15.0, "Series 2", "Category A");
        dataset.addValue(25.0, "Series 2", "Category B");

        domainAxis = new CategoryAxis("Domain");
        rangeAxis = new NumberAxis("Range");
        plot = new CategoryPlot(dataset, domainAxis, rangeAxis, renderer);
    }

    @Override
    protected void tearDown() throws Exception {
        renderer = null;
        plot = null;
        dataset = null;
        domainAxis = null;
        rangeAxis = null;
        super.tearDown();
    }

    // =====================================================================
    // CONSTRUCTOR AND BASIC STATE
    // =====================================================================

    /**
     * Test that renderer is created with default state: no generators,
     * empty annotation lists, plot unassigned.
     */
    public void testConstructorInitialization() {
        ConcreteRenderer r = new ConcreteRenderer();
        assertNull("Base item label generator should be null", r.getBaseItemLabelGenerator());
        assertNull("Base tool tip generator should be null", r.getBaseToolTipGenerator());
        assertNull("Base URL generator should be null", r.getBaseURLGenerator());
        assertNotNull("Legend item label generator should not be null",
                r.getLegendItemLabelGenerator());
        assertNull("Legend item tool tip generator should be null",
                r.getLegendItemToolTipGenerator());
        assertNull("Legend item URL generator should be null",
                r.getLegendItemURLGenerator());
    }

    /**
     * Test pass count defaults to 1.
     */
    public void testGetPassCountDefault() {
        assertEquals("Default pass count should be 1", 1, renderer.getPassCount());
    }

    // =====================================================================
    // PLOT ASSIGNMENT
    // =====================================================================

    /**
     * Test setPlot() stores the plot reference.
     */
    public void testSetPlot() {
        renderer.setPlot(plot);
        assertSame("getPlot() should return the assigned plot", plot, renderer.getPlot());
    }

    /**
     * Test setPlot() rejects null argument.
     */
    public void testSetPlotRejectsNull() {
        try {
            renderer.setPlot(null);
            fail("setPlot(null) should throw IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            assertTrue("Exception message should mention 'plot'",
                    e.getMessage().contains("plot"));
        }
    }

    /**
     * Test getPlot() returns null when no plot assigned.
     */
    public void testGetPlotInitiallyNull() {
        assertNull("getPlot() should return null before setPlot() is called",
                renderer.getPlot());
    }

    // =====================================================================
    // ITEM LABEL GENERATORS
    // =====================================================================

    /**
     * Test base item label generator getter/setter.
     */
    public void testBaseItemLabelGenerator() {
        assertNull("Initially null", renderer.getBaseItemLabelGenerator());
        
        CategoryItemLabelGenerator gen = new CategoryItemLabelGenerator() {
            public String generateLabel(CategoryDataset dataset, int row, int column) {
                return "Label";
            }
        };
        renderer.setBaseItemLabelGenerator(gen);
        assertSame("Should store and retrieve the generator", gen,
                renderer.getBaseItemLabelGenerator());
    }

    /**
     * Test series item label generator getter/setter.
     */
    public void testSeriesItemLabelGenerator() {
        CategoryItemLabelGenerator gen = new CategoryItemLabelGenerator() {
            public String generateLabel(CategoryDataset dataset, int row, int column) {
                return "Series Label";
            }
        };
        
        renderer.setSeriesItemLabelGenerator(0, gen);
        assertSame("Should retrieve series-specific generator", gen,
                renderer.getSeriesItemLabelGenerator(0));
        assertNull("Unset series should return null", renderer.getSeriesItemLabelGenerator(1));
    }

    /**
     * Test getItemLabelGenerator() prioritizes series generator over base.
     */
    public void testGetItemLabelGeneratorResolution() {
        CategoryItemLabelGenerator baseGen = new CategoryItemLabelGenerator() {
            public String generateLabel(CategoryDataset dataset, int row, int column) {
                return "Base";
            }
        };
        CategoryItemLabelGenerator seriesGen = new CategoryItemLabelGenerator() {
            public String generateLabel(CategoryDataset dataset, int row, int column) {
                return "Series";
            }
        };
        
        renderer.setBaseItemLabelGenerator(baseGen);
        renderer.setSeriesItemLabelGenerator(0, seriesGen);
        
        // Row 0 with series generator: should return series generator
        assertSame("Should return series generator for row 0", seriesGen,
                renderer.getItemLabelGenerator(0, 0, false));
        
        // Row 1 without series generator: should return base generator
        assertSame("Should return base generator for row 1", baseGen,
                renderer.getItemLabelGenerator(1, 0, false));
        
        // No base generator set: should return null
        renderer.setBaseItemLabelGenerator(null);
        assertNull("Should return null when no series or base generator", 
                renderer.getItemLabelGenerator(1, 0, false));
    }

    /**
     * Test setSeriesItemLabelGenerator() with notify parameter.
     */
    public void testSetSeriesItemLabelGeneratorWithNotify() {
        CategoryItemLabelGenerator gen = new CategoryItemLabelGenerator() {
            public String generateLabel(CategoryDataset dataset, int row, int column) {
                return "Label";
            }
        };
        
        // Should accept notify=false without exception
        renderer.setSeriesItemLabelGenerator(0, gen, false);
        assertSame("Generator should be stored regardless of notify flag", gen,
                renderer.getSeriesItemLabelGenerator(0));
        
        // Should accept notify=true
        CategoryItemLabelGenerator gen2 = new CategoryItemLabelGenerator() {
            public String generateLabel(CategoryDataset dataset, int row, int column) {
                return "Label2";
            }
        };
        renderer.setSeriesItemLabelGenerator(1, gen2, true);
        assertSame("Generator should be stored", gen2,
                renderer.getSeriesItemLabelGenerator(1));
    }

    // =====================================================================
    // TOOL TIP GENERATORS
    // =====================================================================

    /**
     * Test base tool tip generator getter/setter.
     */
    public void testBaseToolTipGenerator() {
        assertNull("Initially null", renderer.getBaseToolTipGenerator());
        
        CategoryToolTipGenerator gen = new CategoryToolTipGenerator() {
            public String generateToolTip(CategoryDataset dataset, int row, int column) {
                return "Tooltip";
            }
        };
        renderer.setBaseToolTipGenerator(gen);
        assertSame("Should store and retrieve", gen, renderer.getBaseToolTipGenerator());
    }

    /**
     * Test series tool tip generator getter/setter.
     */
    public void testSeriesToolTipGenerator() {
        CategoryToolTipGenerator gen = new CategoryToolTipGenerator() {
            public String generateToolTip(CategoryDataset dataset, int row, int column) {
                return "Series Tooltip";
            }
        };
        
        renderer.setSeriesToolTipGenerator(0, gen);
        assertSame("Should retrieve series-specific generator", gen,
                renderer.getSeriesToolTipGenerator(0));
    }

    /**
     * Test getToolTipGenerator() resolution order: series -> base.
     */
    public void testGetToolTipGeneratorResolution() {
        CategoryToolTipGenerator baseGen = new CategoryToolTipGenerator() {
            public String generateToolTip(CategoryDataset dataset, int row, int column) {
                return "Base";
            }
        };
        CategoryToolTipGenerator seriesGen = new CategoryToolTipGenerator() {
            public String generateToolTip(CategoryDataset dataset, int row, int column) {
                return "Series";
            }
        };
        
        renderer.setBaseToolTipGenerator(baseGen);
        renderer.setSeriesToolTipGenerator(0, seriesGen);
        
        assertSame("Should return series generator for row 0", seriesGen,
                renderer.getToolTipGenerator(0, 0, false));
        assertSame("Should return base generator for row 1", baseGen,
                renderer.getToolTipGenerator(1, 0, false));
    }

    /**
     * Test setSeriesToolTipGenerator() with notify parameter.
     */
    public void testSetSeriesToolTipGeneratorWithNotify() {
        CategoryToolTipGenerator gen = new CategoryToolTipGenerator() {
            public String generateToolTip(CategoryDataset dataset, int row, int column) {
                return "Tooltip";
            }
        };
        
        renderer.setSeriesToolTipGenerator(0, gen, false);
        assertSame("Generator should be stored", gen, renderer.getSeriesToolTipGenerator(0));
        
        CategoryToolTipGenerator gen2 = new CategoryToolTipGenerator() {
            public String generateToolTip(CategoryDataset dataset, int row, int column) {
                return "Tooltip2";
            }
        };
        renderer.setSeriesToolTipGenerator(1, gen2, true);
        assertSame("Generator should be stored", gen2, renderer.getSeriesToolTipGenerator(1));
    }

    // =====================================================================
    // URL GENERATORS
    // =====================================================================

    /**
     * Test base URL generator getter/setter.
     */
    public void testBaseURLGenerator() {
        assertNull("Initially null", renderer.getBaseURLGenerator());
        
        CategoryURLGenerator gen = new CategoryURLGenerator() {
            public String generateURL(CategoryDataset dataset, int row, int column) {
                return "http://example.com";
            }
        };
        renderer.setBaseURLGenerator(gen);
        assertSame("Should store and retrieve", gen, renderer.getBaseURLGenerator());
    }

    /**
     * Test series URL generator getter/setter.
     */
    public void testSeriesURLGenerator() {
        CategoryURLGenerator gen = new CategoryURLGenerator() {
            public String generateURL(CategoryDataset dataset, int row, int column) {
                return "http://series.com";
            }
        };
        
        renderer.setSeriesURLGenerator(0, gen);
        assertSame("Should retrieve series-specific generator", gen,
                renderer.getSeriesURLGenerator(0));
    }

    /**
     * Test getURLGenerator() resolution order: series -> base.
     */
    public void testGetURLGeneratorResolution() {
        CategoryURLGenerator baseGen = new CategoryURLGenerator() {
            public String generateURL(CategoryDataset dataset, int row, int column) {
                return "http://base.com";
            }
        };
        CategoryURLGenerator seriesGen = new CategoryURLGenerator() {
            public String generateURL(CategoryDataset dataset, int row, int column) {
                return "http://series.com";
            }
        };
        
        renderer.setBaseURLGenerator(baseGen);
        renderer.setSeriesURLGenerator(0, seriesGen);
        
        assertSame("Should return series generator for row 0", seriesGen,
                renderer.getURLGenerator(0, 0, false));
        assertSame("Should return base generator for row 1", baseGen,
                renderer.getURLGenerator(1, 0, false));
    }

    /**
     * Test setSeriesURLGenerator() with notify parameter.
     */
    public void testSetSeriesURLGeneratorWithNotify() {
        CategoryURLGenerator gen = new CategoryURLGenerator() {
            public String generateURL(CategoryDataset dataset, int row, int column) {
                return "http://url.com";
            }
        };
        
        renderer.setSeriesURLGenerator(0, gen, false);
        assertSame("Generator should be stored", gen, renderer.getSeriesURLGenerator(0));
    }

    // =====================================================================
    // LEGEND ITEM GENERATORS
    // =====================================================================

    /**
     * Test legend item label generator cannot be set to null.
     */
    public void testSetLegendItemLabelGeneratorRejectsNull() {
        try {
            renderer.setLegendItemLabelGenerator(null);
            fail("setLegendItemLabelGenerator(null) should throw IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            assertTrue("Exception message should mention 'generator'",
                    e.getMessage().contains("generator"));
        }
    }

    /**
     * Test legend item label generator getter/setter.
     */
    public void testLegendItemLabelGenerator() {
        CategorySeriesLabelGenerator gen = new StandardCategorySeriesLabelGenerator();
        renderer.setLegendItemLabelGenerator(gen);
        assertSame("Should store and retrieve", gen, renderer.getLegendItemLabelGenerator());
    }

    /**
     * Test legend item tool tip generator getter/setter (nullable).
     */
    public void testLegendItemToolTipGenerator() {
        assertNull("Initially null", renderer.getLegendItemToolTipGenerator());
        
        CategorySeriesLabelGenerator gen = new StandardCategorySeriesLabelGenerator();
        renderer.setLegendItemToolTipGenerator(gen);
        assertSame("Should store and retrieve", gen, renderer.getLegendItemToolTipGenerator());
        
        // Should accept null
        renderer.setLegendItemToolTipGenerator(null);
        assertNull("Should allow null", renderer.getLegendItemToolTipGenerator());
    }

    /**
     * Test legend item URL generator getter/setter (nullable).
     */
    public void testLegendItemURLGenerator() {
        assertNull("Initially null", renderer.getLegendItemURLGenerator());
        
        CategorySeriesLabelGenerator gen = new StandardCategorySeriesLabelGenerator();
        renderer.setLegendItemURLGenerator(gen);
        assertSame("Should store and retrieve", gen, renderer.getLegendItemURLGenerator());
        
        renderer.setLegendItemURLGenerator(null);
        assertNull("Should allow null", renderer.getLegendItemURLGenerator());
    }

    // =====================================================================
    // ANNOTATIONS
    // =====================================================================

    /**
     * Test addAnnotation() to foreground layer (default).
     */
    public void testAddAnnotationDefaultForeground() {
        MockCategoryAnnotation annotation = new MockCategoryAnnotation();
        renderer.setPlot(plot);
        renderer.addAnnotation(annotation);
        // Verify no exception thrown and annotation was added
        // (no public getter for annotations, but removeAnnotation confirms presence)
        assertTrue("removeAnnotation should return true for added annotation",
                renderer.removeAnnotation(annotation));
    }

    /**
     * Test addAnnotation() rejects null.
     */
    public void testAddAnnotationRejectsNull() {
        try {
            renderer.addAnnotation(null);
            fail("addAnnotation(null) should throw IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            assertTrue("Exception message should mention 'annotation'",
                    e.getMessage().contains("annotation"));
        }
    }

    /**
     * Test addAnnotation() with explicit layer.
     */
    public void testAddAnnotationWithLayer() {
        MockCategoryAnnotation bgAnnotation = new MockCategoryAnnotation();
        MockCategoryAnnotation fgAnnotation = new MockCategoryAnnotation();
        renderer.setPlot(plot);
        
        renderer.addAnnotation(bgAnnotation, Layer.BACKGROUND);
        renderer.addAnnotation(fgAnnotation, Layer.FOREGROUND);
        
        assertTrue("Background annotation should be removable",
                renderer.removeAnnotation(bgAnnotation));
        assertTrue("Foreground annotation should be removable",
                renderer.removeAnnotation(fgAnnotation));
    }

    /**
     * Test removeAnnotation() returns true for existing annotation.
     */
    public void testRemoveAnnotationExists() {
        MockCategoryAnnotation annotation = new MockCategoryAnnotation();
        renderer.setPlot(plot);
        renderer.addAnnotation(annotation);
        
        assertTrue("removeAnnotation should return true", renderer.removeAnnotation(annotation));
    }

    /**
     * Test removeAnnotation() returns false for non-existent annotation.
     */
    public void testRemoveAnnotationNotExists() {
        MockCategoryAnnotation annotation = new MockCategoryAnnotation();
        
        assertFalse("removeAnnotation should return false for annotation never added",
                renderer.removeAnnotation(annotation));
    }

    /**
     * Test removeAnnotations() clears all annotations.
     */
    public void testRemoveAnnotations() {
        MockCategoryAnnotation annotation1 = new MockCategoryAnnotation();
        MockCategoryAnnotation annotation2 = new MockCategoryAnnotation();
        renderer.setPlot(plot);
        renderer.addAnnotation(annotation1, Layer.FOREGROUND);
        renderer.addAnnotation(annotation2, Layer.BACKGROUND);
        
        renderer.removeAnnotations();
        
        assertFalse("Foreground annotation should be removed", 
                renderer.removeAnnotation(annotation1));
        assertFalse("Background annotation should be removed",
                renderer.removeAnnotation(annotation2));
    }

    // =====================================================================
    // LEGEND ITEMS
    // =====================================================================

    /**
     * Test getLegendItem() returns null when plot is not set.
     */
    public void testGetLegendItemNoPlot() {
        assertNull("getLegendItem should return null when plot is null",
                renderer.getLegendItem(0, 0));
    }

    /**
     * Test getLegendItem() with valid dataset and series.
     */
    public void testGetLegendItemValid() {
        renderer.setPlot(plot);
        LegendItem item = renderer.getLegendItem(0, 0);
        
        assertNotNull("Should return a legend item", item);
        assertEquals("Legend item series index should match", 0, item.getSeriesIndex());
        assertEquals("Legend item dataset index should match", 0, item.getDatasetIndex());
    }

    /**
     * Test getLegendItems() returns empty collection when plot is null.
     */
    public void testGetLegendItemsNoPlot() {
        LegendItemCollection items = renderer.getLegendItems();
        assertNotNull("Should return non-null collection", items);
        assertEquals("Collection should be empty", 0, items.getItemCount());
    }

    /**
     * Test getLegendItems() returns collection with items for dataset series.
     */
    public void testGetLegendItemsValid() {
        renderer.setPlot(plot);
        LegendItemCollection items = renderer.getLegendItems();
        
        assertNotNull("Should return non-null collection", items);
        assertEquals("Should contain one item per visible series", 2, items.getItemCount());
    }

    // =====================================================================
    // INITIALIZATION AND STATE
    // =====================================================================

    /**
     * Test initialise() sets row and column counts from dataset.
     */
    public void testInitialiseSetsDimensions() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        PlotRenderingInfo info = new PlotRenderingInfo(new ChartRenderingInfo());
        
        renderer.setPlot(plot);
        CategoryItemRendererState state = renderer.initialise(g2, dataArea, plot, dataset, info);
        
        assertEquals("Row count should be 2", 2, renderer.getRowCount());
        assertEquals("Column count should be 2", 2, renderer.getColumnCount());
        assertNotNull("Should return a state object", state);
        
        g2.dispose();
    }

    /**
     * Test initialise() with null dataset sets row/column count to 0.
     */
    public void testInitialiseNullDataset() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        PlotRenderingInfo info = new PlotRenderingInfo(new ChartRenderingInfo());
        
        renderer.setPlot(plot);
        CategoryItemRendererState state = renderer.initialise(g2, dataArea, plot, null, info);
        
        assertEquals("Row count should be 0 for null dataset", 0, renderer.getRowCount());
        assertEquals("Column count should be 0 for null dataset", 0, renderer.getColumnCount());
        assertNotNull("Should return a state object", state);
        
        g2.dispose();
    }

    /**
     * Test getRowCount() and getColumnCount().
     */
    public void testGetRowAndColumnCount() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        renderer.setPlot(plot);
        renderer.initialise(g2, dataArea, plot, dataset, null);
        
        assertEquals("getRowCount() should return 2", 2, renderer.getRowCount());
        assertEquals("getColumnCount() should return 2", 2, renderer.getColumnCount());
        
        g2.dispose();
    }

    // =====================================================================
    // FINDING RANGE BOUNDS
    // =====================================================================

    /**
     * Test findRangeBounds() returns null for null dataset.
     */
    public void testFindRangeBoundsNullDataset() {
        assertNull("findRangeBounds(null) should return null",
                renderer.findRangeBounds(null));
    }

    /**
     * Test findRangeBounds() for empty dataset.
     */
    public void testFindRangeBoundsEmptyDataset() {
        DefaultCategoryDataset emptyDataset = new DefaultCategoryDataset();
        assertNull("findRangeBounds() for empty dataset should return null",
                renderer.findRangeBounds(emptyDataset));
    }

    /**
     * Test findRangeBounds() with data.
     */
    public void testFindRangeBoundsWithData() {
        assertNotNull("findRangeBounds() should return a Range",
                renderer.findRangeBounds(dataset));
    }

    /**
     * Test findRangeBounds() with includeInterval parameter.
     */
    public void testFindRangeBoundsWithIncludeInterval() {
        org.jfree.data.Range r1 = renderer.findRangeBounds(dataset, false);
        org.jfree.data.Range r2 = renderer.findRangeBounds(dataset, true);
        
        assertNotNull("Should return Range with includeInterval=false", r1);
        assertNotNull("Should return Range with includeInterval=true", r2);
    }

    // =====================================================================
    // EQUALS AND HASH CODE
    // =====================================================================

    /**
     * Test equals() with same object.
     */
    public void testEqualsWithSelf() {
        assertTrue("Renderer should equal itself", renderer.equals(renderer));
    }

    /**
     * Test equals() with different type.
     */
    public void testEqualsWithDifferentType() {
        assertFalse("Renderer should not equal non-renderer object",
                renderer.equals("not a renderer"));
    }

    /**
     * Test equals() with another renderer with same state.
     */
    public void testEqualsWithSameState() {
        ConcreteRenderer other = new ConcreteRenderer();
        assertTrue("Renderers with same initial state should be equal",
                renderer.equals(other));
    }

    /**
     * Test equals() with different base item label generator.
     */
    public void testEqualsWithDifferentBaseItemLabelGenerator() {
        ConcreteRenderer other = new ConcreteRenderer();
        CategoryItemLabelGenerator gen = new CategoryItemLabelGenerator() {
            public String generateLabel(CategoryDataset dataset, int row, int column) {
                return "Label";
            }
        };
        renderer.setBaseItemLabelGenerator(gen);
        
        assertFalse("Renderers with different generators should not be equal",
                renderer.equals(other));
    }

    /**
     * Test hashCode() consistency.
     */
    public void testHashCodeConsistency() {
        int hash1 = renderer.hashCode();
        int hash2 = renderer.hashCode();
        assertEquals("hashCode() should be consistent", hash1, hash2);
    }

    // =====================================================================
    // CLONE
    // =====================================================================

    /**
     * Test clone() creates independent copy.
     */
    public void testClone() throws CloneNotSupportedException {
        ConcreteRenderer cloned = (ConcreteRenderer) renderer.clone();
        
        assertNotSame("Cloned object should be distinct", renderer, cloned);
        assertEquals("Cloned object should be equal", renderer, cloned);
    }

    /**
     * Test clone() with base item label generator.
     */
    public void testCloneWithBaseItemLabelGenerator() throws CloneNotSupportedException {
        CategoryItemLabelGenerator gen = new CategoryItemLabelGenerator() {
            public String generateLabel(CategoryDataset dataset, int row, int column) {
                return "Cloneable Label";
            }
        };
        renderer.setBaseItemLabelGenerator(gen);
        
        // Note: This test will fail if the generator is not PublicCloneable.
        // The production code throws CloneNotSupportedException.
        try {
            ConcreteRenderer cloned = (ConcreteRenderer) renderer.clone();
            assertNotNull("Clone should complete", cloned);
        } catch (CloneNotSupportedException e) {
            // Expected if generator is not cloneable
            assertTrue("Expected exception if generator not cloneable",
                    e.getMessage().contains("not cloneable"));
        }
    }

    // =====================================================================
    // ITEM MIDDLE CALCULATION
    // =====================================================================

    /**
     * Test getItemMiddle() delegates to axis.
     */
    public void testGetItemMiddle() {
        double middle = renderer.getItemMiddle("Series 1", "Category A", dataset,
                domainAxis, new Rectangle2D.Double(0, 0, 100, 100),
                org.jfree.chart.util.RectangleEdge.BOTTOM);
        
        assertTrue("Item middle should be within data area", middle >= 0 && middle <= 100);
    }

    // =====================================================================
    // DRAWING SUPPLIER
    // =====================================================================

    /**
     * Test getDrawingSupplier() returns null when plot not set.
     */
    public void testGetDrawingSupplierNoPlot() {
        assertNull("getDrawingSupplier() should return null when plot is null",
                renderer.getDrawingSupplier());
    }

    /**
     * Test getDrawingSupplier() returns plot's drawing supplier.
     */
    public void testGetDrawingSupplierWithPlot() {
        renderer.setPlot(plot);
        // Drawing supplier may be null if plot doesn't have one configured
        Object supplier = renderer.getDrawingSupplier();
        // Just verify no exception
        assertNotNull("Plot should have a drawing supplier",
                plot.getDrawingSupplier());
    }

    // =====================================================================
    // BACKGROUND AND OUTLINE
    // =====================================================================

    /**
     * Test drawBackground() delegates to plot.
     */
    public void testDrawBackground() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        // Should not throw
        renderer.drawBackground(g2, plot, dataArea);
        
        g2.dispose();
    }

    /**
     * Test drawOutline() delegates to plot.
     */
    public void testDrawOutline() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        // Should not throw
        renderer.drawOutline(g2, plot, dataArea);
        g2.dispose();
    }

    // =====================================================================
    // DOMAIN LINE DRAWING
    // =====================================================================

    /**
     * Test drawDomainLine() rejects null paint.
     */
    public void testDrawDomainLineRejectsNullPaint() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        try {
            renderer.drawDomainLine(g2, plot, dataArea, 50.0, null,
                    new java.awt.BasicStroke());
            fail("drawDomainLine() with null paint should throw IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            assertTrue("Exception message should mention 'paint'",
                    e.getMessage().contains("paint"));
        }
        
        g2.dispose();
    }

    /**
     * Test drawDomainLine() rejects null stroke.
     */
    public void testDrawDomainLineRejectsNullStroke() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        try {
            renderer.drawDomainLine(g2, plot, dataArea, 50.0, Color.BLACK, null);
            fail("drawDomainLine() with null stroke should throw IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            assertTrue("Exception message should mention 'stroke'",
                    e.getMessage().contains("stroke"));
        }
        
        g2.dispose();
    }

    /**
     * Test drawDomainLine() executes with valid arguments.
     */
    public void testDrawDomainLineValid() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        // Should not throw with valid arguments
        renderer.drawDomainLine(g2, plot, dataArea, 50.0, Color.BLACK,
                new java.awt.BasicStroke());
        
        g2.dispose();
    }

    // =====================================================================
    // RANGE LINE DRAWING
    // =====================================================================

    /**
     * Test drawRangeLine() with value outside range returns without drawing.
     */
    public void testDrawRangeLineOutsideRange() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        NumberAxis axis = new NumberAxis("Test");
        axis.setRange(0, 50);
        
        // Value 100 is outside range [0, 50], should return early
        renderer.drawRangeLine(g2, plot, axis, dataArea, 100.0, Color.BLACK,
                new java.awt.BasicStroke());
        
        g2.dispose();
    }

    /**
     * Test drawRangeLine() with value inside range executes.
     */
    public void testDrawRangeLineInsideRange() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        NumberAxis axis = new NumberAxis("Test");
        axis.setRange(0, 50);
        
        // Value 25 is inside range [0, 50]
        renderer.drawRangeLine(g2, plot, axis, dataArea, 25.0, Color.BLACK,
                new java.awt.BasicStroke());
        
        g2.dispose();
    }

    // =====================================================================
    // DOMAIN MARKER DRAWING
    // =====================================================================

    /**
     * Test drawDomainMarker() with invalid category index returns early.
     */
    public void testDrawDomainMarkerInvalidCategory() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        org.jfree.chart.plot.CategoryMarker marker = new org.jfree.chart.plot.CategoryMarker(
                "InvalidCategory");
        
        renderer.setPlot(plot);
        renderer.drawDomainMarker(g2, plot, domainAxis, marker, dataArea);
        
        g2.dispose();
    }

    /**
     * Test drawDomainMarker() with valid category executes.
     */
    public void testDrawDomainMarkerValidCategory() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        org.jfree.chart.plot.CategoryMarker marker = new org.jfree.chart.plot.CategoryMarker(
                "Category A");
        marker.setPaint(Color.RED);
        
        renderer.setPlot(plot);
        renderer.drawDomainMarker(g2, plot, domainAxis, marker, dataArea);
        
        g2.dispose();
    }

    // =====================================================================
    // RANGE MARKER DRAWING
    // =====================================================================

    /**
     * Test drawRangeMarker() with ValueMarker outside range returns early.
     */
    public void testDrawRangeMarkerValueOutsideRange() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        NumberAxis axis = new NumberAxis("Test");
        axis.setRange(0, 50);
        
        org.jfree.chart.plot.ValueMarker marker = new org.jfree.chart.plot.ValueMarker(100.0);
        
        renderer.setPlot(plot);
        renderer.drawRangeMarker(g2, plot, axis, marker, dataArea);
        
        g2.dispose();
    }

    /**
     * Test drawRangeMarker() with ValueMarker inside range executes.
     */
    public void testDrawRangeMarkerValueInsideRange() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        NumberAxis axis = new NumberAxis("Test");
        axis.setRange(0, 50);
        
        org.jfree.chart.plot.ValueMarker marker = new org.jfree.chart.plot.ValueMarker(25.0);
        marker.setPaint(Color.BLUE);
        
        renderer.setPlot(plot);
        renderer.drawRangeMarker(g2, plot, axis, marker, dataArea);
        
        g2.dispose();
    }

    /**
     * Test drawRangeMarker() with IntervalMarker outside range returns early.
     */
    public void testDrawRangeMarkerIntervalOutsideRange() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        NumberAxis axis = new NumberAxis("Test");
        axis.setRange(0, 50);
        
        org.jfree.chart.plot.IntervalMarker marker = new org.jfree.chart.plot.IntervalMarker(
                60.0, 80.0);
        
        renderer.setPlot(plot);
        renderer.drawRangeMarker(g2, plot, axis, marker, dataArea);
        
        g2.dispose();
    }

    /**
     * Test drawRangeMarker() with IntervalMarker intersecting range executes.
     */
    public void testDrawRangeMarkerIntervalIntersecting() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        NumberAxis axis = new NumberAxis("Test");
        axis.setRange(0, 50);
        
        org.jfree.chart.plot.IntervalMarker marker = new org.jfree.chart.plot.IntervalMarker(
                30.0, 60.0);
        marker.setPaint(Color.GREEN);
        
        renderer.setPlot(plot);
        renderer.drawRangeMarker(g2, plot, axis, marker, dataArea);
        
        g2.dispose();
    }

    // =====================================================================
    // ANNOTATIONS
    // =====================================================================

    /**
     * Test drawAnnotations() with foreground layer.
     */
    public void testDrawAnnotationsForeground() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        renderer.setPlot(plot);
        renderer.addAnnotation(new MockCategoryAnnotation(), Layer.FOREGROUND);
        
        // Should execute without exception
        renderer.drawAnnotations(g2, dataArea, domainAxis, rangeAxis,
                Layer.FOREGROUND, null);
        
        g2.dispose();
    }

    /**
     * Test drawAnnotations() with background layer.
     */
    public void testDrawAnnotationsBackground() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        renderer.setPlot(plot);
        renderer.addAnnotation(new MockCategoryAnnotation(), Layer.BACKGROUND);
        
        // Should execute without exception
        renderer.drawAnnotations(g2, dataArea, domainAxis, rangeAxis,
                Layer.BACKGROUND, null);
        
        g2.dispose();
    }

    /**
     * Test drawAnnotations() with empty annotation list.
     */
    public void testDrawAnnotationsEmpty() {
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();
        Rectangle2D dataArea = new Rectangle2D.Double(0, 0, 100, 100);
        
        // Should execute without exception
        renderer.drawAnnotations(g2, dataArea, domainAxis, rangeAxis,
                Layer.FOREGROUND, null);
        
        g2.dispose();
    }

    // =====================================================================
    // ENTITY ADDITION
    // =====================================================================

    /**
     * Test addEntity() rejects null hotspot.
     */
    public void testAddEntityRejectsNullHotspot() {
        org.jfree.chart.entity.EntityCollection entities =
                new org.jfree.chart.entity.StandardEntityCollection();
        
        try {
            renderer.addEntity(entities, null, dataset, 0, 0, false);
            fail("addEntity() with null hotspot should throw IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            assertTrue("Exception message should mention 'hotspot'",
                    e.getMessage().contains("hotspot"));
        }
    }

    /**
     * Test addEntity() with valid hotspot.
     */
    public void testAddEntityValidHotspot() {
        org.jfree.chart.entity.EntityCollection entities =
                new org.jfree.chart.entity.StandardEntityCollection();
        java.awt.Shape hotspot = new java.awt.geom.Rectangle2D.Double(0, 0, 10, 10);
        
        renderer.addEntity(entities, hotspot, dataset, 0, 0, false);
        
        assertEquals("Entity should be added to collection", 1, entities.getEntityCount());
    }

    /**
     * Test addEntity() with explicit coordinates.
     */
    public void testAddEntityWithCoordinates() {
        org.jfree.chart.entity.EntityCollection entities =
                new org.jfree.chart.entity.StandardEntityCollection();
        java.awt.Shape hotspot = new java.awt.geom.Rectangle2D.Double(0, 0, 10, 10);
        
        renderer.addEntity(entities, hotspot, dataset, 0, 0, false, 5.0, 5.0);
        
        assertEquals("Entity should be added to collection", 1, entities.getEntityCount());
    }

    /**
     * Test addEntity() with null hotspot and explicit coordinates creates default shape.
     */
    public void testAddEntityNullHotspotWithCoordinates() {
        renderer.setPlot(plot);
        org.jfree.chart.entity.EntityCollection entities =
                new org.jfree.chart.entity.StandardEntityCollection();
        
        // Null hotspot should create default Ellipse2D shape
        renderer.addEntity(entities, null, dataset, 0, 0, false, 50.0, 50.0);
        
        assertEquals("Entity should be created with default shape", 1, entities.getEntityCount());
    }

    // =====================================================================
    // DOMAIN AND RANGE AXIS ACCESSORS
    // =====================================================================

    /**
     * Test getDomainAxis() returns axis for dataset.
     */
    public void testGetDomainAxis() {
        renderer.setPlot(plot);
        CategoryAxis axis = renderer.getDomainAxis(plot, dataset);
        
        assertNotNull("Should return a domain axis", axis);
    }

    /**
     * Test getRangeAxis() returns axis by index.
     */
    public void testGetRangeAxisValid() {
        renderer.setPlot(plot);
        org.jfree.chart.axis.ValueAxis axis = renderer.getRangeAxis(plot, 0);
        
        assertNotNull("Should return a range axis", axis);
    }

    /**
     * Test getRangeAxis() falls back to default when index not found.
     */
    public void testGetRangeAxisFallback() {
        renderer.setPlot(plot);
        org.jfree.chart.axis.ValueAxis axis = renderer.getRangeAxis(plot, 999);
        
        assertNotNull("Should return default range axis", axis);
    }

    // =====================================================================
    // HELPER CLASS: MOCK ANNOTATION
    // =====================================================================

    /**
     * Mock implementation of CategoryAnnotation for testing.
     */
    private static class MockCategoryAnnotation implements CategoryAnnotation {
        public void draw(Graphics2D g2, CategoryPlot plot, Rectangle2D dataArea,
                CategoryAxis domainAxis, org.jfree.chart.axis.ValueAxis rangeAxis,
                int rendererIndex, PlotRenderingInfo info) {
            // No-op for testing
        }

        public Object clone() throws CloneNotSupportedException {
            return super.clone();
        }
    }
}
