package org.mockito.internal.invocation;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

import java.lang.reflect.Array;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.hamcrest.Matcher;
import org.junit.Test;
import org.mockito.invocation.Invocation;
import org.mockito.invocation.Location;
import org.mockito.internal.matchers.CapturesArguments;
import org.mockito.internal.matchers.MatcherDecorator;
import org.mockito.internal.matchers.VarargMatcher;

@SuppressWarnings({"rawtypes", "unchecked"})
public class InvocationMatcherTest {
    private static Method method(String name) { return method(Object.class, name); }


    private static Method method(Class<?> owner, String name) {
        try {
            return owner.getMethod(name);
        } catch (NoSuchMethodException exception) {
            throw new IllegalStateException(exception);
        }
    }


    // ----------------------------------------
    // Constructor tests
    // ----------------------------------------

    @Test
    public void testConstructorWithEmptyMatchersList_ShouldConvertArgumentsToMatchers() {
        Invocation invocation = mock(Invocation.class);
        when(invocation.getArguments()).thenReturn(new Object[]{"arg1", "arg2"});

        InvocationMatcher matcher = new InvocationMatcher(invocation, Collections.<Matcher>emptyList());
        List<Matcher> matchers = matcher.getMatchers();
        assertNotNull(matchers);
        assertFalse("matchers should not be empty for non-empty arguments", matchers.isEmpty());
        // verify that the matchers are the ones generated by ArgumentsProcessor,
        // which are typically Equals matchers. At minimum they are not null.
        for (Matcher m : matchers) {
            assertNotNull(m);
        }
    }

    @Test
    public void testConstructorWithNonEmptyMatchersList_ShouldUseGivenMatchers() {
        Invocation inv = mock(Invocation.class);
        Matcher matcher1 = mock(Matcher.class);
        Matcher matcher2 = mock(Matcher.class);
        List<Matcher> inputMatchers = Arrays.asList(matcher1, matcher2);

        InvocationMatcher matcher = new InvocationMatcher(inv, inputMatchers);
        List<Matcher> result = matcher.getMatchers();
        assertSame("should use the provided list", inputMatchers, result);
        assertSame(matcher1, result.get(0));
        assertSame(matcher2, result.get(1));
    }

    // ----------- getMethod() -----------

    @Test
    public void testGetMethod_ShouldReturnInvocationMethod() throws Exception {
        Invocation inv = mock(Invocation.class);
        Method expectedMethod = Object.class.getMethod("toString");
        when(inv.getMethod()).thenReturn(expectedMethod);

        InvocationMatcher matcher = new InvocationMatcher(inv);
        assertSame(expectedMethod, matcher.getMethod());
    }

    // ----------- getInvocation() -----------

    @Test
    public void testGetInvocation_ShouldReturnInvocation() {
        Invocation inv = mock(Invocation.class);
        InvocationMatcher matcher = new InvocationMatcher(inv);
        assertSame(inv, matcher.getInvocation());
    }

    // ----------- getMatchers() -----------

    @Test
    public void testGetMatchers_ShouldReturnMatchersList() {
        Invocation inv = mock(Invocation.class);
        Matcher m1 = mock(Matcher.class);
        Matcher m2 = mock(Matcher.class);
        List<Matcher> matchers = Arrays.asList(m1, m2);
        InvocationMatcher matcher = new InvocationMatcher(inv, matchers);
        assertSame(matchers, matcher.getMatchers());
    }

    // ----------- toString() -----------

    @Test
    public void testToString_ShouldNotBeNull() {
        Invocation inv = mock(Invocation.class);
        when(inv.getMethod()).thenReturn(method(Object.class, "toString"));
        when(inv.getLocation()).thenReturn(mock(Location.class));

        InvocationMatcher matcher = new InvocationMatcher(inv);
        String str = matcher.toString();
        assertNotNull(str);
        assertFalse(str.isEmpty());
    }

    // ----------- matches(Invocation) -----------

    @Test
    public void testMatches_SameMockAndSameMethodAndMatchingArgs_ShouldReturnTrue() throws Exception {
        Object mockObject = new Object();
        Method method = Object.class.getMethod("equals", Object.class);

        Invocation inv1 = mock(Invocation.class);
        when(inv1.getMock()).thenReturn(mockObject);
        when(inv1.getMethod()).thenReturn(method);
        when(inv1.getArguments()).thenReturn(new Object[]{mockObject});

        Invocation inv2 = mock(Invocation.class);
        when(inv2.getMock()).thenReturn(mockObject);
        when(inv2.getMethod()).thenReturn(method);
        when(inv2.getArguments()).thenReturn(new Object[]{mockObject});

        InvocationMatcher matcher = new InvocationMatcher(inv1);
        assertTrue(matcher.matches(inv2));
    }

    @Test
    public void testMatches_DifferentMock_ShouldReturnFalse() throws Exception {
        Method method = Object.class.getMethod("toString");
        Invocation inv1 = mock(Invocation.class);
        when(inv1.getMock()).thenReturn(new Object());
        when(inv1.getMethod()).thenReturn(method);

        Invocation inv2 = mock(Invocation.class);
        when(inv2.getMock()).thenReturn(new Object()); // different mock
        when(inv2.getMethod()).thenReturn(method);

        InvocationMatcher matcher = new InvocationMatcher(inv1);
        assertFalse(matcher.matches(inv2));
    }

    @Test
    public void testMatches_DifferentMethod_ShouldReturnFalse() throws Exception {
        Object mockObj = new Object();
        Invocation inv1 = mock(Invocation.class);
        when(inv1.getMock()).thenReturn(mockObj);
        when(inv1.getMethod()).thenReturn(Object.class.getMethod("toString"));

        Invocation inv2 = mock(Invocation.class);
        when(inv2.getMock()).thenReturn(mockObj);
        when(inv2.getMethod()).thenReturn(Object.class.getMethod("hashCode"));

        InvocationMatcher matcher = new InvocationMatcher(inv1);
        assertFalse(matcher.matches(inv2));
    }

    @Test
    public void testMatches_DifferentArgs_ShouldReturnFalse() throws Exception {
        Object mockObj = new Object();
        Method method = Object.class.getMethod("equals", Object.class);
        Invocation inv1 = mock(Invocation.class);
        when(inv1.getMock()).thenReturn(mockObj);
        when(inv1.getMethod()).thenReturn(method);
        when(inv1.getArguments()).thenReturn(new Object[]{"arg1"});

        Invocation inv2 = mock(Invocation.class);
        when(inv2.getMock()).thenReturn(mockObj);
        when(inv2.getMethod()).thenReturn(method);
        when(inv2.getArguments()).thenReturn(new Object[]{"arg2"}); // different

        InvocationMatcher matcher = new InvocationMatcher(inv1);
        assertFalse(matcher.matches(inv2));
    }

    // ----------- hasSameMethod(Invocation) -----------

    @Test
    public void testHasSameMethod_SameNameAndSameParamTypes_ShouldReturnTrue() throws Exception {
        Method m = String.class.getMethod("indexOf", String.class);
        Invocation inv1 = mock(Invocation.class);
        when(inv1.getMethod()).thenReturn(m);
        Invocation inv2 = mock(Invocation.class);
        when(inv2.getMethod()).thenReturn(m);

        InvocationMatcher matcher = new InvocationMatcher(inv1);
        assertTrue(matcher.hasSameMethod(inv2));
    }

    @Test
    public void testHasSameMethod_DifferentParamTypes_ShouldReturnFalse() throws Exception {
        Method m1 = Object.class.getMethod("toString");
        Method m2 = Object.class.getMethod("hashCode");
        Invocation inv1 = mock(Invocation.class);
        when(inv1.getMethod()).thenReturn(m1);
        Invocation inv2 = mock(Invocation.class);
        when(inv2.getMethod()).thenReturn(m2);

        InvocationMatcher matcher = new InvocationMatcher(inv1);
        assertFalse(matcher.hasSameMethod(inv2));
    }

    @Test
    public void testHasSameMethod_NullMethodName_ShouldReturnFalse() throws Exception {
        // Simulate a Method whose getName() returns null (can't happen with real reflection,
        // but we can mock it)
        Method method1 = mock(Method.class);
        when(method1.getName()).thenReturn(null);
        Method method2 = mock(Method.class);
        when(method2.getName()).thenReturn("someName");

        Invocation inv1 = mock(Invocation.class);
        when(inv1.getMethod()).thenReturn(method1);
        Invocation inv2 = mock(Invocation.class);
        when(inv2.getMethod()).thenReturn(method2);

        InvocationMatcher matcher = new InvocationMatcher(inv1);
        assertFalse(matcher.hasSameMethod(inv2));
    }

    // ----------- hasSimilarMethod(Invocation) -----------

    @Test
    public void testHasSimilarMethod_AllConditionsMet_ShouldReturnTrue() throws Exception {
        Object mockObj = new Object();
        Method method = Object.class.getMethod("toString");
        Invocation inv1 = mock(Invocation.class);
        when(inv1.getMethod()).thenReturn(method);
        when(inv1.getMock()).thenReturn(mockObj);

        Invocation candidate = mock(Invocation.class);
        when(candidate.getMethod()).thenReturn(method);
        when(candidate.getMock()).thenReturn(mockObj);
        when(candidate.isVerified()).thenReturn(false);
        when(candidate.getArguments()).thenReturn(new Object[0]); // matched by default

        InvocationMatcher matcher = new InvocationMatcher(inv1);
        assertTrue(matcher.hasSimilarMethod(candidate));
    }

    @Test
    public void testHasSimilarMethod_DifferentMethodName_ShouldReturnFalse() throws Exception {
        Object mockObj = new Object();
        Invocation inv1 = mock(Invocation.class);
        when(inv1.getMethod()).thenReturn(method("toString"));
        when(inv1.getMock()).thenReturn(mockObj);

        Invocation candidate = mock(Invocation.class);
        when(candidate.getMethod()).thenReturn(method("hashCode"));
        when(candidate.getMock()).thenReturn(mockObj);

        InvocationMatcher matcher = new InvocationMatcher(inv1);
        assertFalse(matcher.hasSimilarMethod(candidate));
    }

    @Test
    public void testHasSimilarMethod_VerifiedCandidate_ShouldReturnFalse() throws Exception{
        Object mockObj = new Object();
        Method method = Object.class.getMethod("toString");
        Invocation inv1 = mock(Invocation.class);
        when(inv1.getMethod()).thenReturn(method);
        when(inv1.getMock()).thenReturn(mockObj);

        Invocation candidate = mock(Invocation.class);
        when(candidate.getMethod()).thenReturn(method);
        when(candidate.getMock()).thenReturn(mockObj);
        when(candidate.isVerified()).thenReturn(true); // verified

        InvocationMatcher matcher = new InvocationMatcher(inv1);
        assertFalse(matcher.hasSimilarMethod(candidate));
    }

    @Test
    public void testHasSimilarMethod_DifferentMock_ShouldReturnFalse() throws Exception {
        Method method = Object.class.getMethod("toString");
        Invocation inv1 = mock(Invocation.class);
        when(inv1.getMethod()).thenReturn(method);
        when(inv1.getMock()).thenReturn(new Object());

        Invocation candidate = mock(Invocation.class);
        when(candidate.getMethod()).thenReturn(method);
        when(candidate.getMock()).thenReturn(new Object()); // different mock

        InvocationMatcher matcher = new InvocationMatcher(inv1);
        assertFalse(matcher.hasSimilarMethod(candidate));
    }

    @Test
    public void testHasSimilarMethod_OverloadedButSameArgs_ShouldReturnFalse() throws Exception {
        Object mockObj = new Object();
        // Two different methods with same name but different parameter types
        Method method1 = String.class.getMethod("indexOf", String.class);
        Method method2 = String.class.getMethod("indexOf", int.class);
        Invocation inv = mock(Invocation.class);
        when(inv.getMethod()).thenReturn(method1);
        when(inv.getMock()).thenReturn(mockObj);

        Invocation candidate = mock(Invocation.class);
        when(candidate.getMethod()).thenReturn(method2);
        when(candidate.getMock()).thenReturn(mockObj);
        when(candidate.isVerified()).thenReturn(false);
        // arguments that will match (even though method signatures differ)
        // The argument matching uses the matchers built from inv's arguments,
        // which we need to set to match candidate's arguments.
        when(inv.getArguments()).thenReturn(new Object[]{new Integer(5)});
        when(candidate.getArguments()).thenReturn(new Object[]{new Integer(5)});

        InvocationMatcher matcher = new InvocationMatcher(inv);
        assertFalse(matcher.hasSimilarMethod(candidate));
    }

    // ----------- getLocation() -----------

    @Test
    public void testGetLocation_ShouldReturnInvocationLocation() {
        Invocation inv = mock(Invocation.class);
        Location loc = mock(Location.class);
        when(inv.getLocation()).thenReturn(loc);
        InvocationMatcher matcher = new InvocationMatcher(inv);
        assertSame(loc, matcher.getLocation());
    }

    // ----------- captureArgumentsFrom(Invocation) -----------

    

    @Test
    public void testCaptureArgumentsFrom_VarArgs_CapturesCorrectly() {
        // Setup vararg method
        Method varargMethod = this.getClass().getMethod("varargMethod", String.class, String[].class);
        Invocation inv = mock(Invocation.class);
        when(inv.getMethod()).thenReturn(varargMethod);
        // raw arguments: ["foo", new String[]{"a","b"}]
        Object[] rawArgs = new Object[]{"foo", new String[]{"a", "b"}};
        when(inv.getRawArguments()).thenReturn(rawArgs);
        // getArgumentAt for non-vararg part
        when(inv.getArgumentAt(0, Object.class)).thenReturn("foo");
        // the raw argument for vararg position
        when(inv.getRawArguments()).thenReturn(rawArgs); // as above

        // matchers: one for the fixed param, two for varargs
        Matcher m0 = mock(Matcher.class);
        Matcher m1WithCapture = mock(Matcher.class, withSettings().extraInterfaces(CapturesArguments.class));
        CapturesArguments capturer1 = (CapturesArguments) m1WithCapture;
        Matcher m2WithCapture = mock(Matcher.class, withSettings().extraInterfaces(CapturesArguments.class));
        CapturesArguments capturer2 = (CapturesArguments) m2WithCapture;

        List<Matcher> matchers = Arrays.<Matcher>asList(m0, (Matcher) m1WithCapture, (Matcher) m2WithCapture);
        InvocationMatcher matcherObj = new InvocationMatcher(inv, matchers);

        matcherObj.captureArgumentsFrom(inv);

        // capturer1 should capture from rawArgs[1](undefined) (the array) ?? Actually code:
        // for position indexOfVararg (1) and beyond: it uses invocation.getRawArguments()[position - indexOfVararg]
        // indexOfVararg = rawArgs.length -1 = 1
        // position 1: matchers.get(1) -> m1WithCapture; capture from rawArgs[1-1]=rawArgs[0](undefined)="foo"? Wait careful:
        // The vararg part: for position = indexOfVararg; position < matchers.size(); position++
        // It does: ((CapturesArguments) m).captureFrom(invocation.getRawArguments()[position - indexOfVararg]);
        // So for position=1, raw index = 1-1=0 -> "foo"? That seems wrong. Actually varargs: the rawArguments should include the array as last element.
        // The code treats the vararg positions as mapping to the elements inside the array.
        // But the indexing is off? The code in captureArgumentsFrom: for vararg case, it first loops over positions 0 to indexOfVararg-1 (the fixed args) and calls getArgumentAt(position, Object.class).
        // Then for positions from indexOfVararg to matchers.size()-1, it uses getRawArguments()[position - indexOfVararg]. 
        // If we have rawArgs = ["foo", String[]{"a","b"}], indexOfVararg = 1, matchers.size() is 3.
        // position=1 -> raw index 0 -> "foo"
        // position=2 -> raw index 1 -> the array. That would capture the whole array, not the individual elements. 
        // This suggests the code expects rawArguments to be the expanded varargs, not packed. 
        // But the method getRawArguments() typically returns the arguments as passed to the method, so for varargs, the last argument is an array.
        // So the code may indeed capture the array as a single object. Let's test accordingly.
        // For our test, we'll capture from rawArgs[1](undefined) which is the String[]. So capturer2 should capture the array.
        // So we expect capturer1.captureFrom("foo") and capturer2.captureFrom(new String[]{"a","b"}).
        veriffy(capturer1).captureFrom("foo");
        verify(capturer2).captureFrom(new String[]{ "a", "b" });
    }

    // Helper vararg method for reflection
    public void varargMethod(String s, String... args) {} // used only for Method object

    // ----------- createFrom(List<Invocation>) -----------

    @Test
    public void testCreateFrom_EmptyList_ReturnsEmptyList() {
        List<InvocationMatcher> result = InvocationMatcher.createFrom(Collections.<Invocation> emptyList());
        assertNotNull(result);
        assertTrue(result.isEmpty());
    }

    @Test
    public void testCreateFrom_SingleInvocation_ReturnsListWithOneMatcher() {
        Invocation inv = mock(Invocation.class);
        when(inv.getArguments()).thenReturn(new Object[0]);
        List<Invocation> list = Arrays.asList(inv);
        List<InvocationMatcher> result = InvocationMatcher.createFrom(list);
        assertNotNull(result);
        assertEquals(1, result.size());
        InvocationMatcher matcher = result.get(0);
        assertSame(inv, matcher.getInvocation());
    }

    // ----------- isVarargMatcher (private) via reflection ----------

    @Test
    public void testIsVarargMatcher_DirectVarargMatcher_ReturnsTrue() throws Exception {
        InvocationMatcher matcher = new InvocationMatcher(mock(Invocation.class));
        // private method isVarargMatcher
        java.lang.reflect.Method method = InvocationMatcher.class.getDeclaredMethod("isVarargMatcher", Matcher.class);
        method.setAccessible(true);

        // Create a matcher that implements VarargMatcher
        Matcher varargMatcher = mock(Matcher.class, withSettings().extraInterfaces(VarargMatcher.class));

        Boolean result = (Boolean) method.invoke(matcher, varargMatcher);
        assertTrue(result);
    }

    @Test
    public void testIsVarargMatcher_NonVarargMatcher_ReturnsFalse() throws Exception {
        InvocationMatcher matcher = new InvocationMatcher(mock(Invocation.class));
        java.lang.reflect.Method method = InvocationMatcher.class.getDeclaredMethod("isVarargMatcher", Matcher.class);
 method.setAccessible(true);

        Matcher plainMatcher = mock(Matcher.class);

        Boolean result = (Boolean) method.invoke(matcher, plainMatcher);
        assertFalse(result);
    }
}
